#
# Generated - do not edit!
#
# NOCDDL
#
CND_BASEDIR=`pwd`
# pic32mz_ef_sk__ioexp__11n__freertos configuration
CND_ARTIFACT_DIR_pic32mz_ef_sk__ioexp__11n__freertos=dist/pic32mz_ef_sk__ioexp__11n__freertos/production
CND_ARTIFACT_NAME_pic32mz_ef_sk__ioexp__11n__freertos=DAQiFi_3_0.X.production.hex
CND_ARTIFACT_PATH_pic32mz_ef_sk__ioexp__11n__freertos=dist/pic32mz_ef_sk__ioexp__11n__freertos/production/DAQiFi_3_0.X.production.hex
