/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9 at Fri Mar 30 16:30:48 2018. */

#include "DaqifiOutMessage.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t DaqifiOutMessage_fields[66] = {
    PB_FIELD(  1, UINT32  , OPTIONAL, STATIC  , FIRST, DaqifiOutMessage, msg_time_stamp, msg_time_stamp, 0),
    PB_FIELD(  2, SINT32  , REPEATED, STATIC  , OTHER, DaqifiOutMessage, analog_in_data, msg_time_stamp, 0),
    PB_FIELD(  3, FLOAT   , REPEATED, STATIC  , OTHER, DaqifiOutMessage, analog_in_data_float, analog_in_data, 0),
    PB_FIELD(  4, UINT32  , REPEATED, STATIC  , OTHER, DaqifiOutMessage, analog_in_data_ts, analog_in_data_float, 0),
    PB_FIELD(  5, BYTES   , OPTIONAL, STATIC  , OTHER, DaqifiOutMessage, digital_data, analog_in_data_ts, 0),
    PB_FIELD(  6, UINT32  , REPEATED, STATIC  , OTHER, DaqifiOutMessage, digital_data_ts, digital_data, 0),
    PB_FIELD(  7, UINT32  , REPEATED, STATIC  , OTHER, DaqifiOutMessage, analog_out_data, digital_data_ts, 0),
    PB_FIELD(  8, UINT32  , OPTIONAL, STATIC  , OTHER, DaqifiOutMessage, device_status, analog_out_data, 0),
    PB_FIELD(  9, UINT32  , OPTIONAL, STATIC  , OTHER, DaqifiOutMessage, pwr_status, device_status, 0),
    PB_FIELD( 10, UINT32  , OPTIONAL, STATIC  , OTHER, DaqifiOutMessage, batt_status, pwr_status, 0),
    PB_FIELD( 11, SINT32  , OPTIONAL, STATIC  , OTHER, DaqifiOutMessage, temp_status, batt_status, 0),
    PB_FIELD( 16, UINT32  , OPTIONAL, STATIC  , OTHER, DaqifiOutMessage, timestamp_freq, temp_status, 0),
    PB_FIELD( 17, UINT32  , OPTIONAL, STATIC  , OTHER, DaqifiOutMessage, analog_in_port_num, timestamp_freq, 0),
    PB_FIELD( 18, UINT32  , OPTIONAL, STATIC  , OTHER, DaqifiOutMessage, analog_in_port_num_priv, analog_in_port_num, 0),
    PB_FIELD( 19, BYTES   , OPTIONAL, STATIC  , OTHER, DaqifiOutMessage, analog_in_port_type, analog_in_port_num_priv, 0),
    PB_FIELD( 20, BYTES   , OPTIONAL, STATIC  , OTHER, DaqifiOutMessage, analog_in_port_av_rse, analog_in_port_type, 0),
    PB_FIELD( 21, BYTES   , OPTIONAL, STATIC  , OTHER, DaqifiOutMessage, analog_in_port_rse, analog_in_port_av_rse, 0),
    PB_FIELD( 22, BYTES   , OPTIONAL, STATIC  , OTHER, DaqifiOutMessage, analog_in_port_enabled, analog_in_port_rse, 0),
    PB_FIELD( 23, FLOAT   , REPEATED, STATIC  , OTHER, DaqifiOutMessage, analog_in_port_av_range, analog_in_port_enabled, 0),
    PB_FIELD( 24, FLOAT   , REPEATED, STATIC  , OTHER, DaqifiOutMessage, analog_in_port_av_range_priv, analog_in_port_av_range, 0),
    PB_FIELD( 25, FLOAT   , REPEATED, STATIC  , OTHER, DaqifiOutMessage, analog_in_port_range, analog_in_port_av_range_priv, 0),
    PB_FIELD( 26, FLOAT   , REPEATED, STATIC  , OTHER, DaqifiOutMessage, analog_in_port_range_priv, analog_in_port_range, 0),
    PB_FIELD( 27, UINT32  , OPTIONAL, STATIC  , OTHER, DaqifiOutMessage, analog_in_res, analog_in_port_range_priv, 0),
    PB_FIELD( 28, UINT32  , OPTIONAL, STATIC  , OTHER, DaqifiOutMessage, analog_in_res_priv, analog_in_res, 0),
    PB_FIELD( 29, FLOAT   , REPEATED, STATIC  , OTHER, DaqifiOutMessage, analog_in_int_scale_m, analog_in_res_priv, 0),
    PB_FIELD( 30, FLOAT   , REPEATED, STATIC  , OTHER, DaqifiOutMessage, analog_in_int_scale_m_priv, analog_in_int_scale_m, 0),
    PB_FIELD( 31, FLOAT   , REPEATED, STATIC  , OTHER, DaqifiOutMessage, analog_in_cal_m, analog_in_int_scale_m_priv, 0),
    PB_FIELD( 32, FLOAT   , REPEATED, STATIC  , OTHER, DaqifiOutMessage, analog_in_cal_b, analog_in_cal_m, 0),
    PB_FIELD( 33, FLOAT   , REPEATED, STATIC  , OTHER, DaqifiOutMessage, analog_in_cal_m_priv, analog_in_cal_b, 0),
    PB_FIELD( 34, FLOAT   , REPEATED, STATIC  , OTHER, DaqifiOutMessage, analog_in_cal_b_priv, analog_in_cal_m_priv, 0),
    PB_FIELD( 35, UINT32  , OPTIONAL, STATIC  , OTHER, DaqifiOutMessage, digital_port_num, analog_in_cal_b_priv, 0),
    PB_FIELD( 36, BYTES   , OPTIONAL, STATIC  , OTHER, DaqifiOutMessage, digital_port_type, digital_port_num, 0),
    PB_FIELD( 37, BYTES   , OPTIONAL, STATIC  , OTHER, DaqifiOutMessage, digital_port_dir, digital_port_type, 0),
    PB_FIELD( 38, UINT32  , OPTIONAL, STATIC  , OTHER, DaqifiOutMessage, analog_out_port_num, digital_port_dir, 0),
    PB_FIELD( 39, BYTES   , OPTIONAL, STATIC  , OTHER, DaqifiOutMessage, analog_out_port_type, analog_out_port_num, 0),
    PB_FIELD( 40, UINT32  , OPTIONAL, STATIC  , OTHER, DaqifiOutMessage, analog_out_res, analog_out_port_type, 0),
    PB_FIELD( 41, FLOAT   , REPEATED, STATIC  , OTHER, DaqifiOutMessage, analog_out_port_av_range, analog_out_res, 0),
    PB_FIELD( 42, FLOAT   , OPTIONAL, STATIC  , OTHER, DaqifiOutMessage, analog_out_port_range, analog_out_port_av_range, 0),
    PB_FIELD( 43, BYTES   , OPTIONAL, STATIC  , OTHER, DaqifiOutMessage, ip_addr, analog_out_port_range, 0),
    PB_FIELD( 44, BYTES   , OPTIONAL, STATIC  , OTHER, DaqifiOutMessage, net_mask, ip_addr, 0),
    PB_FIELD( 45, BYTES   , OPTIONAL, STATIC  , OTHER, DaqifiOutMessage, gateway, net_mask, 0),
    PB_FIELD( 46, BYTES   , OPTIONAL, STATIC  , OTHER, DaqifiOutMessage, primary_dns, gateway, 0),
    PB_FIELD( 47, BYTES   , OPTIONAL, STATIC  , OTHER, DaqifiOutMessage, secondary_dns, primary_dns, 0),
    PB_FIELD( 48, BYTES   , OPTIONAL, STATIC  , OTHER, DaqifiOutMessage, mac_addr, secondary_dns, 0),
    PB_FIELD( 49, BYTES   , OPTIONAL, STATIC  , OTHER, DaqifiOutMessage, ip_addr_v6, mac_addr, 0),
    PB_FIELD( 50, BYTES   , OPTIONAL, STATIC  , OTHER, DaqifiOutMessage, sub_pre_length_v6, ip_addr_v6, 0),
    PB_FIELD( 51, BYTES   , OPTIONAL, STATIC  , OTHER, DaqifiOutMessage, gateway_v6, sub_pre_length_v6, 0),
    PB_FIELD( 52, BYTES   , OPTIONAL, STATIC  , OTHER, DaqifiOutMessage, primary_dns_v6, gateway_v6, 0),
    PB_FIELD( 53, BYTES   , OPTIONAL, STATIC  , OTHER, DaqifiOutMessage, secondary_dns_v6, primary_dns_v6, 0),
    PB_FIELD( 54, BYTES   , OPTIONAL, STATIC  , OTHER, DaqifiOutMessage, eui_64, secondary_dns_v6, 0),
    PB_FIELD( 55, STRING  , OPTIONAL, STATIC  , OTHER, DaqifiOutMessage, host_name, eui_64, 0),
    PB_FIELD( 56, UINT32  , OPTIONAL, STATIC  , OTHER, DaqifiOutMessage, device_port, host_name, 0),
    PB_FIELD( 57, STRING  , OPTIONAL, STATIC  , OTHER, DaqifiOutMessage, friendly_device_name, device_port, 0),
    PB_FIELD( 58, STRING  , OPTIONAL, STATIC  , OTHER, DaqifiOutMessage, ssid, friendly_device_name, 0),
    PB_FIELD( 59, UINT32  , OPTIONAL, STATIC  , OTHER, DaqifiOutMessage, ssid_strength, ssid, 0),
    PB_FIELD( 60, UINT32  , OPTIONAL, STATIC  , OTHER, DaqifiOutMessage, wifi_security_mode, ssid_strength, 0),
    PB_FIELD( 61, UINT32  , OPTIONAL, STATIC  , OTHER, DaqifiOutMessage, wifi_inf_mode, wifi_security_mode, 0),
    PB_FIELD( 62, STRING  , REPEATED, STATIC  , OTHER, DaqifiOutMessage, av_ssid, wifi_inf_mode, 0),
    PB_FIELD( 63, UINT32  , REPEATED, STATIC  , OTHER, DaqifiOutMessage, av_ssid_strength, av_ssid, 0),
    PB_FIELD( 64, UINT32  , REPEATED, STATIC  , OTHER, DaqifiOutMessage, av_wifi_security_mode, av_ssid_strength, 0),
    PB_FIELD( 65, UINT32  , REPEATED, STATIC  , OTHER, DaqifiOutMessage, av_wifi_inf_mode, av_wifi_security_mode, 0),
    PB_FIELD( 66, STRING  , OPTIONAL, STATIC  , OTHER, DaqifiOutMessage, device_pn, av_wifi_inf_mode, 0),
    PB_FIELD( 67, STRING  , OPTIONAL, STATIC  , OTHER, DaqifiOutMessage, device_hw_rev, device_pn, 0),
    PB_FIELD( 68, STRING  , OPTIONAL, STATIC  , OTHER, DaqifiOutMessage, device_fw_rev, device_hw_rev, 0),
    PB_FIELD( 69, UINT64  , OPTIONAL, STATIC  , OTHER, DaqifiOutMessage, device_sn, device_fw_rev, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
